run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
    - bodyclose
    - gocritic
    - dupl
    - errorlint
    - unconvert
    - misspell
    - dogsled

linters-settings:
  revive:
    # Set confidence to avoid too many minor style warnings initially
    confidence: 0.8
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
