run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    - depguard # Requires manual dependency whitelist configuration
    - lll      # Line length is often a matter of taste
    - wsl      # Extremely pedantic about white space

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
