version: 2

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - bodyclose
    - errorlint
    - misspell
    - whitespace
    - unparam
    - nakedret
    - prealloc
    - errcheck

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unparam
        - prealloc
        - errcheck
