run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
    - bodyclose
    - gocritic
    - dupl
    - errorlint
    - misspell
    - dogsled
    - whitespace
    - unparam
    - nakedret
    - prealloc

linters-settings:
  revive:
    confidence: 0.8
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  govet:
    enable-all: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  # Exclude common test-related noise
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
